In [1]:
import pandas as pd
import numpy as np
from extract import extract_all
from transform_staging import staging
from transform_core import core

In [2]:
data=extract_all()
data=staging(data)
data=core(data)

In [3]:
dim_data={}

In [4]:
print(data)

{'customers':                             customer_id                customer_unique_id  \
0      06b8999e2fba1a1fbc88172c00ba8bc7  861eff4711a542e4b93843c6dd7febb0
1      18955e83d337fd6b2def6b18a428ac77  290c77bc529b7ac935b93aa66c333dc3
2      4e7b3e00288586ebd08712fdd0374a03  060e732b5b29e8181a18229c7b0b2b5e
3      b2b6027bc5c5109e529d4dc6358b12c3  259dac757896d24d7702b9acbbff3f3c
4      4f2d8ab171c80ec8364f7c12e35b23ad  345ecd01c38d18a9036ed96c73b8d066
...                                 ...                               ...
99436  17ddf5dd5d51696bb3d7c6291687be6f  1a29b476fee25c95fbafc67c5ac95cf8
99437  e7b71a9017aa05c9a7fd292d714858e8  d52a67c98be1cf6a5c84435bd38d095d
99438  5e28dfe12db7fb50a4b2f691faecea5e  e9f50caf99f032f0bf3c55141f019d99
99439  56b18e2166679b8a959d72dd06da27f9  73c2643a0a458b49f58cea58833b192e
99440  274fa6071e5e17fe303b9748641082c8  84732c5050c01db9b23e19ba39899398

       customer_zip_code_prefix          customer_city customer_state
0                         14409                 Franca             SP
1                          9790  Sao Bernardo Do Campo             SP
2                          1151              Sao Paulo             SP
3                          8775        Mogi Das Cruzes             SP
4                         13056               Campinas             SP
...                         ...                    ...            ...
99436                      3937              Sao Paulo             SP
99437                      6764        Taboao Da Serra             SP
99438                     60115              Fortaleza             CE
99439                     92120                 Canoas             RS
99440                      6703                  Cotia             SP

[96096 rows x 5 columns], 'geolocation':          geolocation_zip_code_prefix  geolocation_lat  geolocation_lng  \
0                               1037       -23.545621       -46.639292
1                               1046       -23.546081       -46.644820
2                               1046       -23.546129       -46.642951
3                               1041       -23.544392       -46.639499
4                               1035       -23.541578       -46.641607
...                              ...              ...              ...
1000158                        99950       -28.068639       -52.010705
1000159                        99900       -27.877125       -52.224882
1000160                        99950       -28.071855       -52.014716
1000161                        99980       -28.388932       -51.846871
1000162                        99950       -28.070104       -52.018658

        geolocation_city geolocation_state
0              sao paulo                SP
1              sao paulo                SP
2              sao paulo                SP
3              sao paulo                SP
4              sao paulo                SP
...                  ...               ...
1000158         tapejara                RS
1000159   getulio vargas                RS
1000160         tapejara                RS
1000161  david canabarro                RS
1000162         tapejara                RS

[1000163 rows x 5 columns], 'orders':                                order_id                       customer_id  \
0      e481f51cbdc54678b7cc49136f2d6af7  9ef432eb6251297304e76186b10a928d
1      53cdb2fc8bc7dce0b6741e2150273451  b0830fb4747a6c6d20dea0b8c802d7ef
2      47770eb9100c2d0c44946d9cf07ec65d  41ce2a54c0b03bf3443c3d931a367089
3      949d5b44dbf5de918fe9c16f97b45f8a  f88197465ea7920adcdbec7375364d82
4      ad21c59c0840e6cb83a9ceb5573f8159  8ab97904e6daea8866dbdbc4fb7aad2c
...                                 ...                               ...
99436  9c5dedf39a927c1b2549525ed64a053c  39bd1228ee8140590ac3aca26f2dfe00
99437  63943bddc261676b46f01ca7ac2f7bd8  1fca14ff2861355f6e5f14306ff977a7
99438  83c1379a015df1e13d02aae0204711ab  1aa71eb042121263aafbe80c1b562c9c
99439  11c177c8e97725db2631073c19f07b62  b331b74b18dc79bcdf6532d51e1637c1
99440  66dea50a8b16d9b4dee7af250b4be1a5  edb027a75a1449115f6b43211ae02a24

      order_status order_purchase_timestamp   order_approved_at  \
0        delivered      2017-10-02 10:56:33 2017-10-02 11:07:15
1        delivered      2018-07-24 20:41:37 2018-07-26 03:24:27
2        delivered      2018-08-08 08:38:49 2018-08-08 08:55:23
3        delivered      2017-11-18 19:28:06 2017-11-18 19:45:59
4        delivered      2018-02-13 21:18:39 2018-02-13 22:20:29
...            ...                      ...                 ...
99436    delivered      2017-03-09 09:54:05 2017-03-09 09:54:05
99437    delivered      2018-02-06 12:58:58 2018-02-06 13:10:37
99438    delivered      2017-08-27 14:46:43 2017-08-27 15:04:16
99439    delivered      2018-01-08 21:28:27 2018-01-08 21:36:21
99440    delivered      2018-03-08 20:57:30 2018-03-09 11:20:28

      order_delivered_carrier_date order_delivered_customer_date  \
0              2017-10-04 19:55:00           2017-10-10 21:25:13
1              2018-07-26 14:31:00           2018-08-07 15:27:45
2              2018-08-08 13:50:00           2018-08-17 18:06:29
3              2017-11-22 13:39:59           2017-12-02 00:28:42
4              2018-02-14 19:46:34           2018-02-16 18:17:02
...                            ...                           ...
99436          2017-03-10 11:18:03           2017-03-17 15:08:01
99437          2018-02-07 23:22:42           2018-02-28 17:37:56
99438          2017-08-28 20:52:26           2017-09-21 11:24:17
99439          2018-01-12 15:35:03           2018-01-25 23:32:54
99440          2018-03-09 22:11:59           2018-03-16 13:08:30

      order_estimated_delivery_date  delivery_days
0                        2017-10-18            8.0
1                        2018-08-13           13.0
2                        2018-09-04            9.0
3                        2017-12-15           13.0
4                        2018-02-26            2.0
...                             ...            ...
99436                    2017-03-28            8.0
99437                    2018-03-02           22.0
99438                    2017-09-27           24.0
99439                    2018-02-15           17.0
99440                    2018-04-03            7.0

[98832 rows x 9 columns], 'order_items':                                 order_id  order_item_id  \
0       00010242fe8c5a6d1ba2dd792cb16214              1
1       00018f77f2f0320c557190d7a144bdd3              1
2       000229ec398224ef6ca0657da4fc703e              1
3       00024acbcdf0a6daa1e931b038114c75              1
4       00042b26cf59d7ce69dfabb4e55b4fd9              1
...                                  ...            ...
112645  fffc94f6ce00a00581880bf54a75a037              1
112646  fffcd46ef2263f404302a634eb57f7eb              1
112647  fffce4705a9662cd70adb13d4a31832d              1
112648  fffe18544ffabc95dfada21779c9644f              1
112649  fffe41c64501cc87c801fd61db3f6244              1

                              product_id                         seller_id  \
0       4244733e06e7ecb4970a6e2683c13e61  48436dade18ac8b2bce089ec2a041202
1       e5f2d52b802189ee658865ca93d83a8f  dd7ddc04e1b6c2c614352b383efe2d36
2       c777355d18b72b67abbeef9df44fd0fd  5b51032eddd242adc84c38acab88f23d
3       7634da152a4610f1595efa32f14722fc  9d7a1d34a5052409006425275ba1c2b4
4       ac6c3623068f30de03045865e4e10089  df560393f3a51e74553ab94004ba5c87
...                                  ...                               ...
112645  4aa6014eceb682077f9dc4bffebc05b0  b8bc237ba3788b23da09c0f1f3a3288c
112646  32e07fd915822b0765e448c4dd74c828  f3c38ab652836d21de61fb8314b69182
112647  72a30483855e2eafc67aee5dc2560482  c3cfdc648177fdbbbb35635a37472c53
112648  9c422a519119dcad7575db5af1ba540e  2b3e4a2a3ea8e01938cabda2a3e5cc79
112649  350688d9dc1e75ff97be326363655e01  f7ccf836d21b2fb1de37564105216cc1

        shipping_limit_date   price  freight_value
0       2017-09-19 09:45:35   58.90          13.29
1       2017-05-03 11:05:13  239.90          19.93
2       2018-01-18 14:48:30  199.00          17.87
3       2018-08-15 10:10:18   12.99          12.79
4       2017-02-13 13:57:51  199.90          18.14
...                     ...     ...            ...
112645  2018-05-02 04:11:01  299.99          43.41
112646  2018-07-20 04:31:48  350.00          36.53
112647  2017-10-30 17:14:25   99.90          16.95
112648  2017-08-21 00:04:32   55.99           8.72
112649  2018-06-12 17:10:13   43.00          12.79

[112267 rows x 7 columns], 'order_payments':                                order_id  total_price  common_type
0      00010242fe8c5a6d1ba2dd792cb16214        72.19  credit_card
1      00018f77f2f0320c557190d7a144bdd3       259.83  credit_card
2      000229ec398224ef6ca0657da4fc703e       216.87  credit_card
3      00024acbcdf0a6daa1e931b038114c75        25.78  credit_card
4      00042b26cf59d7ce69dfabb4e55b4fd9       218.04  credit_card
...                                 ...          ...          ...
99435  fffc94f6ce00a00581880bf54a75a037       343.40       boleto
99436  fffcd46ef2263f404302a634eb57f7eb       386.53       boleto
99437  fffce4705a9662cd70adb13d4a31832d       116.85  credit_card
99438  fffe18544ffabc95dfada21779c9644f        64.71  credit_card
99439  fffe41c64501cc87c801fd61db3f6244        55.79  credit_card

[99440 rows x 3 columns], 'order_reviews':                               review_id                          order_id  \
57039  6322c405c0f34bf3ad870fd1a6b1fced  0006ec9db01a64e59a68b2c340bf65a7
95730  00800678dcf28b0ea0caef2147b6945d  000aed2e25dbad2f9ddb70584c5a2ded
10287  4ff9a24999699f7104ed23fec2563351  00130c0eee84a3d909e75bc08c5c3ca1
66534  048baba3f11436d12b06dab572aafc21  001e7cf2ad6bef3ade12ebc56ceaf0f3
18747  78412bf6c796b43df999fd87750d28ea  002175704e8b209f61b9ad5cfd92b60e
...                                 ...                               ...
84395  38746e8fc612cf700a2e1bffd8412a39  ffcb98e21b0bf085baf42b16a67732ef
33349  cb864e5bb7299e87df2bf1eb66fddbcd  ffd6f465cab015b452d398ac1f5d978a
82409  027011a097af2b7cbd1de0a5d23a98f9  ffe0d6b7d4772a7380978ef7f0885b89
93935  3e46e959e03570ecdd743b9736758c54  ffe48cb3d8485e0cb0405e21192e592f
5580   df4fd9c21862ce248509293f20a4d5bd  ffea20c7630343a6cd9e09858c1295cd

       review_score   review_comment_title  \
57039             5                    Boa
95730             1   produto não entregue
10287             5        Super Recomendo
66534             1                Pessima
18747             4              Recomendo
...             ...                    ...
84395             5              Recomendo
33349             4                  Ótimo
82409             5                  Ótima
93935             3              Recomendo
5580              5  plenamente satisfeita

                                  review_comment_message review_creation_date  \
57039              Excelente serviço de compras on line.  2018-07-31 00:00:00
95730  Mudo minha opinião assim que receber o produto...  2018-05-19 00:00:00
10287  Produto entregue adequadamente e muito rápido,...  2018-06-14 00:00:00
66534                O produto chegou e estragou sozinho  2018-06-05 00:00:00
18747  Produto como descrito. Mas não gostei pq o som...  2018-05-03 00:00:00
...                                                  ...                  ...
84395                                   Muito satisfeita  2018-06-13 00:00:00
33349  O produto chegou antes da data prevista, é tud...  2018-05-04 00:00:00
82409                                                NaN  2018-07-28 00:00:00
93935  Encomendem um pouco mais, não tem o tamanho in...  2018-07-13 00:00:00
5580   recomendo a loja...meu produto chegou antes do...  2018-06-05 00:00:00

      review_answer_timestamp
57039     2018-08-01 23:05:10
95730     2018-05-22 10:52:24
10287     2018-06-14 19:50:09
66534     2018-06-06 19:01:54
18747     2018-05-06 13:42:10
...                       ...
84395     2018-06-13 20:28:42
33349     2018-05-05 01:32:43
82409     2018-07-29 02:33:56
93935     2018-07-13 18:07:36
5580      2018-06-06 02:07:24

[11550 rows x 7 columns], 'products':                              product_id              product_category_name  \
0      1e9e8ef04dbcff4541ed26657ea517e5                         perfumaria
1      3aa071139cb16b67ca9e5dea641aaa2f                              artes
2      96bd76ec8810374ed1b65e291975717f                      esporte_lazer
3      cef67bcfe19066a932b7673e239eb23d                              bebes
4      9dc1a7de274444849c219cff195d0b71              utilidades_domesticas
...                                 ...                                ...
32323  a0b7d5a992ccda646f2d34e418fff5a0                   moveis_decoracao
32324  bf4538d88321d0fd4412a93c974510e6  construcao_ferramentas_iluminacao
32325  9a7c6041fa9592d9d9ef6cfe62a71f8c                    cama_mesa_banho
32326  83808703fc0706a22e264b9d75f04a2e             informatica_acessorios
32327  106392145fca363410d287a815be6de4                    cama_mesa_banho

       product_name_lenght  product_description_lenght  product_photos_qty  \
0                     40.0                       287.0                 1.0
1                     44.0                       276.0                 1.0
2                     46.0                       250.0                 1.0
3                     27.0                       261.0                 1.0
4                     37.0                       402.0                 4.0
...                    ...                         ...                 ...
32323                 45.0                        67.0                 2.0
32324                 41.0                       971.0                 1.0
32325                 50.0                       799.0                 1.0
32326                 60.0                       156.0                 2.0
32327                 58.0                       309.0                 1.0

       product_weight_g  product_length_cm  product_height_cm  \
0                 225.0               16.0               10.0
1                1000.0               30.0               18.0
2                 154.0               18.0                9.0
3                 371.0               26.0                4.0
4                 625.0               20.0               17.0
...                 ...                ...                ...
32323           12300.0               40.0               40.0
32324            1700.0               16.0               19.0
32325            1400.0               27.0                7.0
32326             700.0               31.0               13.0
32327            2083.0               12.0                2.0

       product_width_cm product_category_name_english
0                  14.0                     perfumery
1                  20.0                           art
2                  15.0                sports_leisure
3                  26.0                          baby
4                  13.0                    housewares
...                 ...                           ...
32323              40.0               furniture_decor
32324              16.0     construction_tools_lights
32325              27.0                bed_bath_table
32326              20.0         computers_accessories
32327               7.0                bed_bath_table

[32328 rows x 10 columns], 'sellers':                              seller_id  seller_zip_code_prefix  \
0     3442f8959a84dea7ee197c632cb2df15                   13023
1     d1b65fc7debc3361ea86b5f14c68d2e2                   13844
2     ce3ad9de960102d0677a81f5d0bb7b2d                   20031
3     c0f3eea2e14555b6faeea3dd58c1b1c3                    4195
4     51a04a8a6bdcb23deccc82b0b80742cf                   12914
...                                ...                     ...
3090  98dddbc4601dd4443ca174359b237166                   87111
3091  f8201cab383e484733266d1906e2fdfa                   88137
3092  74871d19219c7d518d0090283e03c137                    4650
3093  e603cf3fec55f8697c9059638d6c8eb5                   96080
3094  9e25199f6ef7e7c347120ff175652c3b                   12051

            seller_city seller_state
0              Campinas           SP
1            Mogi Guacu           SP
2        Rio De Janeiro           RJ
3             Sao Paulo           SP
4     Braganca Paulista           SP
...                 ...          ...
3090            Sarandi           PR
3091            Palhoca           SC
3092          Sao Paulo           SP
3093            Pelotas           RS
3094            Taubate           SP

[3095 rows x 4 columns], 'product_category_name_translation':             product_category_name product_category_name_english
0                    beleza_saude                 health_beauty
1          informatica_acessorios         computers_accessories
2                      automotivo                          auto
3                 cama_mesa_banho                bed_bath_table
4                moveis_decoracao               furniture_decor
..                            ...                           ...
66                         flores                       flowers
67             artes_e_artesanato         arts_and_craftmanship
68                fraldas_higiene           diapers_and_hygiene
69  fashion_roupa_infanto_juvenil     fashion_childrens_clothes
70             seguros_e_servicos         security_and_services

[71 rows x 2 columns], 'dim_date':                      date  year  quarter  month month_name  week  week_day  \
0     2017-10-02 10:56:33  2017        4     10    October     0         0
1     2018-07-24 20:41:37  2018        3      7       July     1         1
2     2018-08-08 08:38:49  2018        3      8     August     2         2
3     2017-11-18 19:28:06  2017        4     11   November     5         5
4     2018-02-13 21:18:39  2018        1      2   February     1         1
...                   ...   ...      ...    ...        ...   ...       ...
99436 2017-03-09 09:54:05  2017        1      3      March     3         3
99437 2018-02-06 12:58:58  2018        1      2   February     1         1
99438 2017-08-27 14:46:43  2017        3      8     August     6         6
99439 2018-01-08 21:28:27  2018        1      1    January     0         0
99440 2018-03-08 20:57:30  2018        1      3      March     3         3

             day  is_weekend
0         Monday       False
1        Tuesday       False
2      Wednesday       False
3       Saturday        True
4        Tuesday       False
...          ...         ...
99436   Thursday       False
99437    Tuesday       False
99438     Sunday        True
99439     Monday       False
99440   Thursday       False

[98832 rows x 9 columns]}

In [5]:
data['orders']

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,delivery_days
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,8.0
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,13.0
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,9.0
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,13.0
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,2.0
...,...,...,...,...,...,...,...,...,...
99436,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,delivered,2017-03-09 09:54:05,2017-03-09 09:54:05,2017-03-10 11:18:03,2017-03-17 15:08:01,2017-03-28,8.0
99437,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02,22.0
99438,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27,24.0
99439,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15,17.0
99440,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03,7.0

In [6]:
dim_data['dim_customer']=pd.merge(data['customers'],data['orders'],on='customer_id')
dim_data['dim_customer']['customer_key']=range(1,len(dim_data['dim_customer'])+1)
dim_data['dim_customer']['valid_from']=dim_data['dim_customer']['order_purchase_timestamp']
dim_data['dim_customer']['valid_to']='9999-12-31'
dim_data['dim_customer']['current']=True
del dim_data['dim_customer']['order_id']
del dim_data['dim_customer']['order_approved_at']
del dim_data['dim_customer']['order_delivered_carrier_date']
del dim_data['dim_customer']['order_delivered_customer_date']
del dim_data['dim_customer']['order_estimated_delivery_date']
del dim_data['dim_customer']['order_purchase_timestamp']
del dim_data['dim_customer']['order_status']
del dim_data['dim_customer']['delivery_days']
dim_data['dim_customer'].head(5)

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,customer_key,valid_from,valid_to,current
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,Franca,SP,1,2017-05-16 15:05:35,9999-12-31,True
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,Sao Bernardo Do Campo,SP,2,2018-01-12 20:48:24,9999-12-31,True
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,Sao Paulo,SP,3,2018-05-19 16:07:45,9999-12-31,True
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,Mogi Das Cruzes,SP,4,2018-03-13 16:06:38,9999-12-31,True
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,Campinas,SP,5,2018-07-29 09:51:30,9999-12-31,True

In [7]:
data['products'].head(5)
dim_data['dim_product']=data['products']
dim_data['dim_product']['product_key']=range(1,len(dim_data['dim_product'])+1)
dim_data['dim_product'].head(5)

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,product_category_name_english,product_key
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0,perfumery,1
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0,art,2
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0,sports_leisure,3
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0,baby,4
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0,housewares,5

In [8]:
data['sellers'].head(5)
dim_data['dim_seller']=data['sellers']
dim_data['dim_seller']['seller_key']=range(1,len(dim_data['dim_seller'])+1)
dim_data['dim_seller'].head(5)

,seller_id,seller_zip_code_prefix,seller_city,seller_state,seller_key
0,3442f8959a84dea7ee197c632cb2df15,13023,Campinas,SP,1
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,Mogi Guacu,SP,2
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,Rio De Janeiro,RJ,3
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,Sao Paulo,SP,4
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,Braganca Paulista,SP,5

In [9]:
data['dim_date']['date_key']=data['dim_date']['date'].dt.strftime('%Y%m%d')
data['dim_date']['date_key']=data['dim_date']['date_key'].astype(int)
dim_data['dim_date']=data['dim_date']

In [10]:
dim_data['fact_orders']=data['order_items']
dim_data['fact_orders']

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14
...,...,...,...,...,...,...,...
112645,fffc94f6ce00a00581880bf54a75a037,1,4aa6014eceb682077f9dc4bffebc05b0,b8bc237ba3788b23da09c0f1f3a3288c,2018-05-02 04:11:01,299.99,43.41
112646,fffcd46ef2263f404302a634eb57f7eb,1,32e07fd915822b0765e448c4dd74c828,f3c38ab652836d21de61fb8314b69182,2018-07-20 04:31:48,350.00,36.53
112647,fffce4705a9662cd70adb13d4a31832d,1,72a30483855e2eafc67aee5dc2560482,c3cfdc648177fdbbbb35635a37472c53,2017-10-30 17:14:25,99.90,16.95
112648,fffe18544ffabc95dfada21779c9644f,1,9c422a519119dcad7575db5af1ba540e,2b3e4a2a3ea8e01938cabda2a3e5cc79,2017-08-21 00:04:32,55.99,8.72
112649,fffe41c64501cc87c801fd61db3f6244,1,350688d9dc1e75ff97be326363655e01,f7ccf836d21b2fb1de37564105216cc1,2018-06-12 17:10:13,43.00,12.79

In [11]:
dim_data['fact_orders']=pd.merge(dim_data['fact_orders'],data['orders'],on='order_id')
dim_data['fact_orders']=pd.merge(dim_data['fact_orders'],data['order_payments'],on='order_id')
dim_data['fact_orders']=pd.merge(dim_data['fact_orders'],data['order_reviews'],on='order_id')

KeyError: 'dim'

In [13]:
dim_data['fact_orders']=pd.merge(dim_data['fact_orders'],dim_data['dim_customer'][['customer_id','customer_key']],on='customer_id')
dim_data['fact_orders']=dim_data['fact_orders'].drop(columns='customer_id')
dim_data['fact_orders']=pd.merge(dim_data['fact_orders'],dim_data['dim_product'][['product_id','product_key']],on='product_id')
dim_data['fact_orders']=dim_data['fact_orders'].drop(columns='product_id')
dim_data['fact_orders']=pd.merge(dim_data['fact_orders'],dim_data['dim_seller'][['seller_id','seller_key']],on='seller_id')
dim_data['fact_orders']=dim_data['fact_orders'].drop(columns='seller_id')
dim_data['fact_orders']=pd.merge(dim_data['fact_orders'],dim_data['dim_date'][['date','date_key']],left_on='order_purchase_timestamp',right_on='date')
dim_data['fact_orders']=dim_data['fact_orders'].drop(columns='order_purchase_timestamp')

In [14]:
dim_data['fact_orders']['order_item_key']=range(1,len(dim_data['fact_orders'])+1)

In [15]:
dim_data['fact_orders'].head(5)

,order_id,order_item_id,shipping_limit_date,price,freight_value,order_status,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,...,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp,customer_key,product_key,seller_key,date,date_key,order_item_key
0,0006ec9db01a64e59a68b2c340bf65a7,1,2018-07-26 17:24:20,74.0,23.32,delivered,2018-07-24 17:24:20,2018-07-25 11:02:00,2018-07-31 01:04:15,2018-08-22,...,Boa,Excelente serviço de compras on line.,2018-07-31 00:00:00,2018-08-01 23:05:10,83017,9476,2464,2018-07-24 17:04:17,20180724,1
1,000aed2e25dbad2f9ddb70584c5a2ded,1,2018-05-16 20:57:03,144.0,8.77,delivered,2018-05-11 20:57:03,2018-05-16 14:26:00,2018-05-18 16:46:31,2018-05-22,...,produto não entregue,Mudo minha opinião assim que receber o produto...,2018-05-19 00:00:00,2018-05-22 10:52:24,30295,29718,999,2018-05-11 20:33:38,20180511,2
2,00130c0eee84a3d909e75bc08c5c3ca1,1,2018-06-14 05:16:24,27.9,7.94,delivered,2018-06-12 05:16:24,2018-06-12 14:22:00,2018-06-13 15:28:25,2018-06-20,...,Super Recomendo,"Produto entregue adequadamente e muito rápido,...",2018-06-14 00:00:00,2018-06-14 19:50:09,84240,25501,1782,2018-06-11 21:17:00,20180611,3
3,001e7cf2ad6bef3ade12ebc56ceaf0f3,1,2018-05-22 10:59:50,35.9,15.20,delivered,2018-05-19 10:59:50,2018-05-21 14:34:00,2018-06-04 18:08:23,2018-06-05,...,Pessima,O produto chegou e estragou sozinho,2018-06-05 00:00:00,2018-06-06 19:01:54,14936,31211,1043,2018-05-19 10:29:23,20180519,4
4,002175704e8b209f61b9ad5cfd92b60e,1,2018-04-26 12:30:57,109.9,13.21,delivered,2018-04-24 17:24:48,2018-04-23 19:03:19,2018-05-02 20:38:44,2018-05-14,...,Recomendo,Produto como descrito. Mas não gostei pq o som...,2018-05-03 00:00:00,2018-05-06 13:42:10,28217,22977,1514,2018-04-22 12:13:25,20180422,5